In [42]:
import numpy as np
import pandas as pd

from plotnine import *

from sklearn.cluster import DBSCAN, KMeans
from sklearn.mixture import GaussianMixture

from sklearn.metrics import silhouette_score

from sklearn.preprocessing import StandardScaler

In [43]:
df = pd.read_csv("auta.csv", index_col=0)
df

                               Cena  Przebieg  Pojemnosc   KM  diesle
Audi A3                  20900.0000  164450.0     1896.0  110    66.9
Audi A4                  25311.4000  182000.0     1900.0  130    75.7
Audi A6                  31500.0000  185000.0     2496.0  170    82.5
Audi A8                 109000.0000  129380.0     4134.0  300    68.1
Audi Q7                 179000.0000   72000.0     3000.0  240    89.1
BMW 316                   6150.0000  186000.0     1600.0  105     1.7
BMW 318                  14500.0000  173980.0     1895.0  118    32.8
BMW 320                  21699.0000  178000.0     2000.0  150    81.4
BMW 520                  55900.0000  149350.0     1998.0  163    65.7
BMW 525                  17110.0000  207000.0     2499.0  163    87.7
BMW 530                  46669.6000  182000.0     3000.0  218    92.2
BMW X5                  139949.5000  107000.0     2993.0  235    84.1
Citroen Berlingo         16800.0000  143000.0     1600.0   90    80.8
Citroen C3               17200.0000   86000.0     1398.0   68    54.7
Citroen C4               23943.4450   98000.0     1560.0  109    67.8
Citroen C4 Picasso       36900.0000  115000.0     1600.0  110    88.2
Citroen C5               20999.5000  145000.0     1997.0  136    79.2
Citroen Xsara             8400.0000  152000.0     1761.0   90    42.5
Citroen Xsara Picasso    13800.0000  150000.0     1800.0   95    63.1
Mazda 3                  30500.0000   98700.0     1598.0  109    41.1
Mazda 323F                8999.0000  170000.0     1600.0   90    37.4
Mazda 6                  26400.0000  147000.0     1998.0  136    74.2
Opel Astra               14900.0000  146000.0     1686.0  100    56.3
Opel Corsa               11900.0000  120000.0     1229.0   75    33.4
Opel Meriva              19900.0000  119000.0     1686.0  100    66.7
Opel Omega                6400.0000  205000.0     2200.0  136    40.9
Opel Vectra              15900.0000  166000.0     1910.0  120    61.6
Opel Zafira              18900.0000  158000.0     1910.0  110    80.6
Peugeot 206              10900.0000  127000.0     1398.0   75    46.6
Peugeot 207              25493.7289   52147.0     1400.0   88    60.1
Peugeot 307              17500.0000  145250.0     1600.0  109    80.7
Peugeot 308              37900.0000   47000.0     1598.0  109    78.3
Peugeot 406               8750.0000  183000.0     1997.0  110    51.6
Peugeot 407              27695.0000  139000.0     1997.0  136    86.8
Peugeot Partner          16000.0000  135000.0     1600.0   90    84.5
Renault Clio             12500.0000  107354.5     1400.0   75    44.9
Renault Espace           18300.0000  167000.0     2000.0  140    76.0
Renault Grand Scenic     23900.0000  139802.5     1900.0  120    90.2
Renault Kangoo           12300.0000  146000.0     1500.0   75    71.5
Renault Laguna           12999.0000  160000.0     1895.5  120    65.3
Renault Megane           14700.0000  136000.0     1598.0  105    51.2
Renault Scenic           13800.0000  155500.0     1870.0  107    64.4
Renault Twingo            8700.0000   63277.0     1200.0   60    10.9
Volkswagen Bora          15390.4450  180000.0     1896.0  110    67.9
Volkswagen Golf          13900.0000  167000.0     1896.0  101    53.9
Volkswagen Passat        21400.0000  181000.0     1900.0  130    81.6
Volkswagen Polo          13800.0000  129000.0     1400.0   70    35.5
Volkswagen Sharan        20500.0000  193000.0     1897.0  115    83.5
Volkswagen Touran        33000.0000  160000.0     1900.0  105    95.3
Volkswagen Transporter   17650.0000  223000.0     2400.0  102    96.2
Volvo S40                29900.0000  135000.0     1900.0  136    68.4
Volvo V40                10047.4500  189322.0     1870.0  115    62.9
Volvo V50                34900.0000  140000.0     1998.0  136    96.4

In [44]:
auta_km = df.copy()
auta_gm = df.copy()
auta_db = df.copy()

In [45]:
sscaler = StandardScaler()

auta_km[auta_km.columns] = sscaler.fit_transform(df[df.columns])

# K-means

In [46]:
scores = []

for i in range(2,7):
  km = KMeans(n_clusters=i).fit(auta_km)
  auta_km['klastry_km'] = km.labels_
  df['klastry_km'] = km.labels_
  score = silhouette_score(df[['Cena']],df['klastry_km'])
  scores.append(score)

## Wartości Silhouette wdg ilości klastrów (KMeans) względem ceny aut:

In [47]:
for index,score in enumerate(scores, 2):
    print(f"{index} klustry: {score}")

2 klustry: 0.8373420255764807
3 klustry: 0.053724704066117734
4 klustry: -0.05451580226954292
5 klustry: -0.09621092663571996
6 klustry: -0.13356592828285066

# Gaussian Mixture

In [48]:
auta_gm[auta_gm.columns] = sscaler.fit_transform(auta_gm[auta_gm.columns])

gm_scores = []

for i in range(2,7):
    print(i)
    gm = GaussianMixture(n_components=i).fit(auta_gm)
    gm_pred = gm.predict(auta_gm)
    auta_gm['klastry_gm'] = gm_pred
    df['klastry_gm'] = gm_pred
    score = silhouette_score(df[['Cena']],df['klastry_gm'])
    gm_scores.append(score)

2
3
4
5
6

## Wartości Silhouette wdg ilości klastrów (GM) względem ceny aut:

In [49]:
for index,score in enumerate(gm_scores, 2):
    print(f"{index} klustry: {score}")

2 klustry: 0.8888746785500887
3 klustry: 0.3274683314504112
4 klustry: 0.0758584855936178
5 klustry: 0.03302282673853458
6 klustry: -0.1493746258966626

# DBSCAN

In [ ]:
db_scores = []

# 0.5, 5 / 1, 5 / 1, 10 / 1.5, 15 / 1.5, 10 / 1.5 , 5 / 2, 5/ 2, 10 / 2, 15 / 2.5 , 5 / 3, 5

In [88]:
auta_db[auta_db.columns] = sscaler.fit_transform(auta_db[auta_db.columns])
       

db = DBSCAN(eps=3,min_samples=5).fit(auta_db)
auta_db['klastry_db'] = db.labels_
df['klastry_db'] = db.labels_
score = silhouette_score(df[['Cena']],df['klastry_db'])
db_scores.append(score)

In [83]:
print(db_scores)

[-0.386932980138605, -0.386932980138605, -0.26911752155703195, -0.10796071846743982, 0.6420164933376616, 0.6420164933376616, 0.6420164933376616, 0.6420164933376616, 0.6420164933376616, 0.6420164933376616, 0.6420164933376616, 0.6884422800329756]

## Wartości Silhouette wdg ilości klastrów (DBSCAN) względem ceny aut:

In [89]:
print(f"EPS 0.5, MIN_SAMPLES 5: {db_scores[1]}")
print(f"EPS 1, MIN_SAMPLES 5: {db_scores[2]}")
print(f"EPS 1, MIN_SAMPLES 10: {db_scores[3]}")
print(f"EPS 1, MIN_SAMPLES 15: {db_scores[4]}")
print(f"EPS 1.5, MIN_SAMPLES 15: {db_scores[5]}")
print(f"EPS 1.5, MIN_SAMPLES 10: {db_scores[6]}")
print(f"EPS 1.5, MIN_SAMPLES 5: {db_scores[7]}")
print(f"EPS 2, MIN_SAMPLES 5: {db_scores[8]}")
print(f"EPS 2, MIN_SAMPLES 10: {db_scores[9]}")
print(f"EPS 2, MIN_SAMPLES 15: {db_scores[10]}")
print(f"EPS 2.5, MIN_SAMPLES 5: {db_scores[11]}")
print(f"EPS 3, MIN_SAMPLES 5: {db_scores[12]}")

EPS 0.5, MIN_SAMPLES 5: -0.386932980138605
EPS 1, MIN_SAMPLES 5: -0.26911752155703195
EPS 1, MIN_SAMPLES 10: -0.10796071846743982
EPS 1, MIN_SAMPLES 15: 0.6420164933376616
EPS 1.5, MIN_SAMPLES 15: 0.6420164933376616
EPS 1.5, MIN_SAMPLES 10: 0.6420164933376616
EPS 1.5, MIN_SAMPLES 5: 0.6420164933376616
EPS 2, MIN_SAMPLES 5: 0.6420164933376616
EPS 2, MIN_SAMPLES 10: 0.6420164933376616
EPS 2, MIN_SAMPLES 15: 0.6420164933376616
EPS 2.5, MIN_SAMPLES 5: 0.6884422800329756
EPS 3, MIN_SAMPLES 5: 0.6884422800329756